### ISSUE TITLE
extending the prototype of an existing custom element should copy over the listeners

### ISSUE THREAD

**Issue by yoshuawuyts** [requireio/custom-element#4]
When extending an existing custom element that wasn't created with `custom-element`, it'd be rad if the existing listeners would be copied over to the `.on` structure rather than being straight up overwritten. That way it's possible to infinitely extend custom components, even if they're not initially set up with `custom-element`. 

The use case I'm picturing for this is having generic components that are self-contained and are just concerned with updating the component itself, and once you use them in an application you can attach glue code listeners that can listen to changes in other parts of your application. Think that would be a neat separation of concerns, hah.

I'm basing this assumption off reading the code, not verified yet so apologies if I'm opening a redundant issue, hah.

**Comment by yoshuawuyts** [comment]
Oh, also without saying: if this is something that get's +1'd I'll open up a PR for this. Thanks!

**Comment by timoxley** [comment]
consider this +1'd. great idea.
